language: rust
rust:
  - stable
  - beta
  - nightly
install:
  - sudo apt-get install build-essential -y
script:
  - cargo build --verbose --workspace
  - cargo doc --verbose --workspace
  - cargo test --verbose --workspace
branches:
  only:
    - master
