language: rust
rust:
  - stable
  - beta
  - nightly
install:
  - sudo apt-get install libselinux1-dev -y
  - sudo apt-get install build-essential -y
  - sudo apt-get install libpcre2-dev -y
script:
  - cargo build -vv --workspace
  - cargo doc -vv --workspace
  - cargo test -vv --workspace
  - cargo clean
  - cargo build -vv --workspace --features "build-static"
  - cargo doc -vv --workspace --features "build-static"
  - cargo clean && cargo test -vv --workspace --features "build-static"
branches:
  only:
    - master
