name: Build
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [stable, beta, nightly]
        include:
          - build: stable
            os: ubuntu-latest
            rust: stable
          - build: beta
            os: ubuntu-latest
            rust: beta
          - build: nightly
            os: ubuntu-latest
            rust: nightly
    steps:
    - uses: actions/checkout@master
    - name: Install Rust (rustup)
      run: rustup update ${{ matrix.rust }} --no-self-update && rustup default ${{ matrix.rust }}
      shell: bash
    - run: sudo apt-get install libselinux1-dev -y
    - run: sudo apt-get install build-essential -y
    - run: sudo apt-get install libpcre2-dev -y
    - run: cargo build -vv --workspace
    - run: cargo doc -vv --workspace
    - run: cargo test -vv --workspace
    - run: cargo clean
    - run: cargo build -vv --workspace --features "build-static-libselinux"
    - run: cargo doc -vv --workspace --features "build-static-libselinux"
    - run: cargo clean && cargo test -vv --workspace --features "build-static-libselinux"

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: rustup update stable && rustup default stable && rustup component add rustfmt
    - run: cargo fmt -- --check
